### ISSUE TITLE
xCore xCoreClass::readStream() 

### ISSUE THREAD

**Issue by nickcounts** [xinabox/xCore#1]
The latest implementation of xCore throws compile errors in readStream():

> declaration of 'uint8_t value' shadows a parameter uint8_t value;

It looks like the intention of `readStream()` is to pass the number of bytes to read from the I2C bus as an argument (based on the call to `Wire.requestFrom`). The following code fixes the shadow parameter and names the argument accordingly.

Starting at line 52:

```Arduino
uint8_t xCoreClass::readStream(byte device, byte bytesToRead){
	uint8_t value;
	value = 0;
	Wire.requestFrom((uint8_t)device, (uint8_t)bytesToRead);
	value = Wire.read();
	return value;
}
```

**Comment by brendanvanbreda** [comment]
@nickcounts thank you for picking it up.
The issue has been resolved. The intention is for `xCoreClass::readStream` is to read allow the user to read an I2C stream and then store data output into a buffer. Examples of implementation still to be added. If any other problem arises feel free to open a new issue.
